/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlbumCover: typeof import('./src/components/album-cover.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PlayBar: typeof import('./src/components/play-bar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SongBox: typeof import('./src/components/song-box.vue')['default']
  }
}
